import { app, BrowserWindow ,Notification,Tray,Menu, App} from 'electron';
import path from "path";
import { pollResource } from './resourceManager';
import { db, initDb } from './database/sqldb';
import { timeDataIPC } from './ipc/timers/timersDataIpc';
import { handleIpcRegistration } from './ipc/ipc_register';


let mainWindow:BrowserWindow=null
app.setAppUserModelId('Its Time');

function forceSingleAppInstance(app:App){
  const isNewInstance=app.requestSingleInstanceLock(null);
  if(!isNewInstance){
    app.quit();
  } else{
    app.on('second-instance',(_0,_1,_2,_3)=>{
      if(mainWindow!=null){

        if(mainWindow.isMinimized()) {mainWindow.restore();mainWindow.focus();return;}
        if (!mainWindow.isVisible())  mainWindow.show(); 
        if(!mainWindow.isFocused()) mainWindow.focus();
      }
    })
  }
}

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;


function hideAppToTray(mainWindow:BrowserWindow){
  let willClose=false;
  
  mainWindow.on('close', (event) => {
    if(willClose){
      return 
    }
    event.preventDefault(); // Stop the app from quitting
    mainWindow.hide();      
    if(app.dock){
      
      app.dock.hide()
    }
  });
  let tray = new Tray(!isDev?path.join(process.resourcesPath,'app-assets','appicon.png'):path.join('./src','app-assets','appicon.png'));
  
  const contextMenu = Menu.buildFromTemplate([
    { label: 'Show App', click: () => mainWindow.show() },
    { label: 'Quit', click: () => {  app.quit(); } }
  ]);
  tray.addListener('double-click',(_1,_2)=>{
    mainWindow.show();
  })
  tray.setToolTip('Its Time');
  tray.setContextMenu(contextMenu);
  app.on("before-quit",()=>{
    willClose=true
  })
}


const isDev=process.env.NODE_ENV!=='production'
// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  mainWindow = new BrowserWindow({
    height: 610,
    minHeight:400,
    minWidth:580,
    width: 860,
    autoHideMenuBar:!isDev,
    webPreferences: {
      
      devTools:isDev,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });
  
  if(!isDev){
    const appMenu=Menu.buildFromTemplate([])
    Menu.setApplicationMenu(appMenu)
  }
  
  hideAppToTray(mainWindow)
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  console.log("Hello")
  initDb();
  
  try{
    db.exec(`
      CREATE TABLE IF NOT EXISTS timers (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        title TEXT,
        message TEXT,
        seconds INTEGER
        )
        `);
      const defaultTimerQuery="INSERT into timers (title,message,seconds) VALUES(?,?,?)"
      const timerCheck=db.prepare('Select * from timers LIMIT 1')
      const row=timerCheck.get()
      if(row==undefined){
        const insertDefaultTimer=db.prepare(defaultTimerQuery)
        const result=insertDefaultTimer.run("Timer","It's Time ", 300);
        if(result.changes>0){
          console.log("default timer added")
        }
        else{
          console.log("Could'nt add timer")
        }
      }
      }
      catch(err){
        console.log(err)
      }
      
      handleIpcRegistration();
      
    };
    
    
    app.on('ready', ()=>{
      
      forceSingleAppInstance(app)
      createWindow()
    });
    
    
    app.on('window-all-closed', () => {
      if (process.platform !== 'darwin') {
        app.quit();
      }
    });
    
    app.on('activate', () => {
      
      if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
      }
    });
    
    
    //Might Use later
    // type SubMenu={
      //     label:string,
      //     click:()=>void
      //   }
      
      //   type Menu={
        //       label:string,
        //       submenu:SubMenu[],
        
        //     }[]
        